name: victormichael
favicon: null
layout_spectrum: 0.8293
typography_spectrum: 0.15638
title: PREMIUM DIGITAL MARKETING STRATEGIES
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#020210'
    - '#50ba94'
    - '#6d6d6d'
    - '#f1961d'
  brandStrength: 1
  lightness: 0.125
  saturation: 0.5625
  rhythmicContrast: 0.75
purpose: []
