name: victormichael
favicon: null
layout_spectrum: 1
typography_spectrum: 0.04444
title: PREMIUM DIGITAL MARKETING STRATEGIES
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#fe7c00'
    - '#fec200'
    - '#cd3d00'
    - '#fee33f'
  brandStrength: 0.875
  lightness: 0.0625
  saturation: 0.05527657503262162
  rhythmicContrast: 1
purpose: []
